// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package order

import (
	"context"

	"ecommerce-demo/app/order/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateOrderReq  = pb.CreateOrderReq
	CreateOrderResp = pb.CreateOrderResp

	ListOrderReq  = pb.ListOrderReq
	ListOrderResp = pb.ListOrderResp
	OrderItem     = pb.OrderItem

	GetOrderDetailReq  = pb.GetOrderDetailReq
	GetOrderDetailResp = pb.GetOrderDetailResp

	CancelOrderReq  = pb.CancelOrderReq
	CancelOrderResp = pb.CancelOrderResp

	ConfirmPayReq  = pb.ConfirmPayReq
	ConfirmPayResp = pb.ConfirmPayResp

	Order interface {
		CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error)
		ConfirmPay(ctx context.Context, in *ConfirmPayReq, opts ...grpc.CallOption) (*ConfirmPayResp, error)
		ListOrder(ctx context.Context, in *ListOrderReq, opts ...grpc.CallOption) (*ListOrderResp, error)
		GetOrderDetail(ctx context.Context, in *GetOrderDetailReq, opts ...grpc.CallOption) (*GetOrderDetailResp, error)
		CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

func (m *defaultOrder) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultOrder) ConfirmPay(ctx context.Context, in *ConfirmPayReq, opts ...grpc.CallOption) (*ConfirmPayResp, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.ConfirmPay(ctx, in, opts...)
}

func (m *defaultOrder) ListOrder(ctx context.Context, in *ListOrderReq, opts ...grpc.CallOption) (*ListOrderResp, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.ListOrder(ctx, in, opts...)
}

func (m *defaultOrder) GetOrderDetail(ctx context.Context, in *GetOrderDetailReq, opts ...grpc.CallOption) (*GetOrderDetailResp, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.GetOrderDetail(ctx, in, opts...)
}

func (m *defaultOrder) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.CancelOrder(ctx, in, opts...)
}
