// Code generated by goctl. DO NOT EDIT.
// Source: stock.proto

package stock

import (
	"context"

	"ecommerce-demo/app/stock/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeductStockReq    = pb.DeductStockReq
	DeductStockResp   = pb.DeductStockResp
	RollbackStockReq  = pb.RollbackStockReq
	RollbackStockResp = pb.RollbackStockResp
	GetStockReq       = pb.GetStockReq
	GetStockResp      = pb.GetStockResp
	BatchGetStockReq  = pb.BatchGetStockReq
	BatchGetStockResp = pb.BatchGetStockResp

	Stock interface {
		DeductStock(ctx context.Context, in *DeductStockReq, opts ...grpc.CallOption) (*DeductStockResp, error)
		RollbackStock(ctx context.Context, in *RollbackStockReq, opts ...grpc.CallOption) (*RollbackStockResp, error)
		GetStock(ctx context.Context, in *GetStockReq, opts ...grpc.CallOption) (*GetStockResp, error)
		BatchGetStock(ctx context.Context, in *BatchGetStockReq, opts ...grpc.CallOption) (*BatchGetStockResp, error)
	}

	defaultStock struct {
		cli zrpc.Client
	}
)

func NewStock(cli zrpc.Client) Stock {
	return &defaultStock{cli: cli}
}

func (m *defaultStock) DeductStock(ctx context.Context, in *DeductStockReq, opts ...grpc.CallOption) (*DeductStockResp, error) {
	client := pb.NewStockClient(m.cli.Conn())
	return client.DeductStock(ctx, in, opts...)
}

func (m *defaultStock) RollbackStock(ctx context.Context, in *RollbackStockReq, opts ...grpc.CallOption) (*RollbackStockResp, error) {
	client := pb.NewStockClient(m.cli.Conn())
	return client.RollbackStock(ctx, in, opts...)
}

func (m *defaultStock) GetStock(ctx context.Context, in *GetStockReq, opts ...grpc.CallOption) (*GetStockResp, error) {
	client := pb.NewStockClient(m.cli.Conn())
	return client.GetStock(ctx, in, opts...)
}

func (m *defaultStock) BatchGetStock(ctx context.Context, in *BatchGetStockReq, opts ...grpc.CallOption) (*BatchGetStockResp, error) {
	client := pb.NewStockClient(m.cli.Conn())
	return client.BatchGetStock(ctx, in, opts...)
}
