// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	address "ecommerce-demo/app/gateway/internal/handler/address"
	cart "ecommerce-demo/app/gateway/internal/handler/cart"
	order "ecommerce-demo/app/gateway/internal/handler/order"
	payment "ecommerce-demo/app/gateway/internal/handler/payment"
	product "ecommerce-demo/app/gateway/internal/handler/product"
	user "ecommerce-demo/app/gateway/internal/handler/user"
	"ecommerce-demo/app/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/order/create",
					Handler: order.CreateOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/order/list",
					Handler: order.ListOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/order/detail",
					Handler: order.GetOrderDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/order/cancel",
					Handler: order.CancelOrderHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/product/:id",
				Handler: product.GetProductHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/product/list",
				Handler: product.ListProductHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/product/list/page",
				Handler: product.ListProductByPageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/product/categories",
				Handler: product.GetCategoriesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/product/add",
				Handler: product.AddProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/product/update",
				Handler: product.UpdateProductHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/product/:id",
				Handler: product.DeleteProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/product/category/add",
				Handler: product.AddCategoryHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/refresh",
				Handler: user.RefreshHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/user/info",
					Handler: user.GetUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/user/logout",
					Handler: user.LogoutHandler(serverCtx),
				},
			}...,
		),
	)

	// ============================================
	// 购物车路由（全部需要认证）
	// ============================================
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/cart/add",
					Handler: cart.AddCartHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cart/list",
					Handler: cart.GetCartHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/cart/update",
					Handler: cart.UpdateCartHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/cart/:product_id",
					Handler: cart.RemoveCartHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/cart/clear",
					Handler: cart.ClearCartHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/cart/select",
					Handler: cart.SelectCartHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/cart/selected",
					Handler: cart.GetSelectedCartHandler(serverCtx),
				},
			}...,
		),
	)

	// ============================================
	// 支付路由
	// ============================================
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/pay/create",
					Handler: payment.CreatePayHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/pay/status/:payment_no",
					Handler: payment.GetPayStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/pay/cancel/:payment_no",
					Handler: payment.CancelPayHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/pay/list",
					Handler: payment.ListPayHandler(serverCtx),
				},
			}...,
		),
	)

	// ============================================
	// 收货地址路由
	// ============================================
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/address/list",
					Handler: address.GetAddressListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/address/:id",
					Handler: address.GetAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/address/add",
					Handler: address.AddAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/address/update",
					Handler: address.UpdateAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/address/:id",
					Handler: address.DeleteAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/address/set-default",
					Handler: address.SetDefaultAddressHandler(serverCtx),
				},
			}...,
		),
	)
}
