// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: product.proto

package server

import (
	"context"

	"ecommerce-demo/app/product/internal/logic"
	"ecommerce-demo/app/product/internal/svc"
	"ecommerce-demo/app/product/pb"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

// 获取商品详情 (这个接口后面我们会做 Redis 高并发缓存)
func (s *ProductServer) GetProduct(ctx context.Context, in *pb.GetProductReq) (*pb.GetProductResp, error) {
	l := logic.NewGetProductLogic(ctx, s.svcCtx)
	return l.GetProduct(in)
}

// 获取商品列表
func (s *ProductServer) ListProduct(ctx context.Context, in *pb.ListProductReq) (*pb.ListProductResp, error) {
	l := logic.NewListProductLogic(ctx, s.svcCtx)
	return l.ListProduct(in)
}

// 添加商品
func (s *ProductServer) AddProduct(ctx context.Context, in *pb.AddProductReq) (*pb.AddProductResp, error) {
	l := logic.NewAddProductLogic(ctx, s.svcCtx)
	return l.AddProduct(in)
}

// 更新商品
func (s *ProductServer) UpdateProduct(ctx context.Context, in *pb.UpdateProductReq) (*pb.UpdateProductResp, error) {
	l := logic.NewUpdateProductLogic(ctx, s.svcCtx)
	return l.UpdateProduct(in)
}

// 删除商品
func (s *ProductServer) DeleteProduct(ctx context.Context, in *pb.DeleteProductReq) (*pb.DeleteProductResp, error) {
	l := logic.NewDeleteProductLogic(ctx, s.svcCtx)
	return l.DeleteProduct(in)
}

// 分页获取商品列表
func (s *ProductServer) ListProductByPage(ctx context.Context, in *pb.ListProductByPageReq) (*pb.ListProductByPageResp, error) {
	l := logic.NewListProductByPageLogic(ctx, s.svcCtx)
	return l.ListProductByPage(in)
}

// 获取商品分类
func (s *ProductServer) GetCategories(ctx context.Context, in *pb.GetCategoriesReq) (*pb.GetCategoriesResp, error) {
	l := logic.NewGetCategoriesLogic(ctx, s.svcCtx)
	return l.GetCategories(in)
}

// 添加商品分类
func (s *ProductServer) AddCategory(ctx context.Context, in *pb.AddCategoryReq) (*pb.AddCategoryResp, error) {
	l := logic.NewAddCategoryLogic(ctx, s.svcCtx)
	return l.AddCategory(in)
}
