// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateOrderReq struct {
	ProductId int64 `json:"productId" validate:"required,min=1"`
	Count     int32 `json:"count" validate:"required,min=1"`
}

type CreateOrderResp struct {
	OrderNo string `json:"orderNo"`
}

type GetProductReq struct {
	Id int64 `path:"id"` // 注意这里用 path 标签，支持 /api/product/1 这种 RESTful 风格
}

type GetProductResp struct {
	Product ProductItem `json:"product"`
}

type GetUserInfoResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
}

type ListProductResp struct {
	Products []ProductItem `json:"products"`
}

type LoginReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type LoginResp struct {
	Id           int64  `json:"id"`
	AccessToken  string `json:"accessToken"`  // 短期令牌 (如: 2小时)
	RefreshToken string `json:"refreshToken"` // 长期令牌 (如: 7天)
}

type LogoutResp struct {
}

type ProductItem struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	Desc         string `json:"desc"`
	Price        int64  `json:"price"` // 返回给前端也是分
	ImageUrl     string `json:"image_url"`
	CategoryId   int64  `json:"category_id"`
	CategoryName string `json:"category_name"`
	Stock        int32  `json:"stock"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken" validate:"required"`
}

type RefreshTokenResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type RegisterReq struct {
	Username string `json:"username" validate:"required,min=4,max=20"`
	Password string `json:"password" validate:"required,min=6"`
}

type RegisterResp struct {
	Id int64 `json:"id"`
}

// ============================================
// 商品管理类型 (管理员接口)
// ============================================

// 添加商品
type AddProductReq struct {
	Name       string `json:"name" vd:"len($)>0 && len($)<=128"`
	Desc       string `json:"desc" vd:"len($)>=0 && len($)<=255"`
	Price      int64  `json:"price" vd:"$>0"`
	Stock      int32  `json:"stock" vd:"$>=0"`
	ImageUrl   string `json:"image_url"`
	CategoryId int64  `json:"category_id"`
}

type AddProductResp struct {
	Id      int64  `json:"id"`
	Message string `json:"message"`
}

// 更新商品
type UpdateProductReq struct {
	Id         int64  `json:"id" vd:"$>0"`
	Name       string `json:"name" vd:"len($)>0 && len($)<=128"`
	Desc       string `json:"desc" vd:"len($)>=0 && len($)<=255"`
	Price      int64  `json:"price" vd:"$>0"`
	ImageUrl   string `json:"image_url"`
	CategoryId int64  `json:"category_id"`
}

type UpdateProductResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

// 删除商品
type DeleteProductReq struct {
	Id int64 `path:"id"`
}

type DeleteProductResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

// 商品分类
type CategoryItem struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	Icon string `json:"icon"`
	Sort int32  `json:"sort"`
}

// 获取商品分类
type GetCategoriesResp struct {
	Categories []CategoryItem `json:"categories"`
}

// 添加分类
type AddCategoryReq struct {
	Name string `json:"name" vd:"len($)>0 && len($)<=32"`
	Icon string `json:"icon"`
	Sort int32  `json:"sort"`
}

type AddCategoryResp struct {
	Id      int64  `json:"id"`
	Message string `json:"message"`
}

// 分页获取商品
type ListProductByPageReq struct {
	CategoryId int64  `form:"category_id,optional"`
	Keyword    string `form:"keyword,optional"`
	Page       int32  `form:"page,optional"`
	PageSize   int32  `form:"page_size,optional"`
}

type ListProductByPageResp struct {
	Products []ProductItem `json:"products"`
	Total    int32        `json:"total"`
	Page     int32        `json:"page"`
	PageSize int32        `json:"page_size"`
}

// ============================================
// 购物车相关类型
// ============================================

type CartItem struct {
	ProductId   int64  `json:"product_id"`
	ProductName string `json:"product_name"`
	Price       int64  `json:"price"`
	ImageUrl    string `json:"image_url"`
	Count       int32  `json:"count"`
	Selected    bool   `json:"selected"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

// 加入购物车
type AddCartReq struct {
	ProductId   int64  `json:"product_id" vd:"$>0"`
	ProductName string `json:"product_name" vd:"len($)>0"`
	Price       int64  `json:"price" vd:"$>0"`
	ImageUrl    string `json:"image_url"`
	Count       int32  `json:"count" vd:"$>0 && $<=99"`
}

type AddCartResp struct {
	Message    string `json:"message"`
	TotalCount int32  `json:"total_count"`
}

// 获取购物车列表
type GetCartResp struct {
	Items       []CartItem `json:"items"`
	TotalCount  int32      `json:"total_count"`
	TotalAmount int64      `json:"total_amount"`
}

// 修改购物车数量
type UpdateCartReq struct {
	ProductId int64 `json:"product_id" vd:"$>0"`
	Count     int32 `json:"count" vd:"$>=0 && $<=99"`
}

type UpdateCartResp struct {
	Message string `json:"message"`
}

// 删除购物车商品
type RemoveCartReq struct {
	ProductId int64 `path:"product_id"`
}

type RemoveCartResp struct {
	Message string `json:"message"`
}

// 清空购物车
type ClearCartResp struct {
	Message      string `json:"message"`
	RemovedCount int32  `json:"removed_count"`
}

// 勾选/取消勾选商品
type SelectCartReq struct {
	ProductId int64 `json:"product_id" vd:"$>0"`
	Selected  bool  `json:"selected"`
}

type SelectCartResp struct {
	Message string `json:"message"`
}

// 获取已选中的商品（用于结算）
type GetSelectedCartResp struct {
	Items         []CartItem `json:"items"`
	SelectedCount int32      `json:"selected_count"`
	TotalAmount   int64      `json:"total_amount"`
}

// 内部请求类型（用于 RPC 调用）
type GetCartReq struct {
	UserId int64 `json:"user_id"`
}

type ClearCartReq struct {
	UserId int64 `json:"user_id"`
}

type GetSelectedCartReq struct {
	UserId int64 `json:"user_id"`
}

// ============================================
// 支付相关类型
// ============================================

type PaymentInfo struct {
	Id         int64  `json:"id"`
	PaymentNo  string `json:"payment_no"`
	OrderNo    string `json:"order_no"`
	Amount     int64  `json:"amount"`
	Status     int32  `json:"status"`
	StatusText string `json:"status_text"`
	PayChannel string `json:"pay_channel"`
	PayTime    int64  `json:"pay_time"`
	ExpireTime int64  `json:"expire_time"`
	CreatedAt  int64  `json:"created_at"`
}

// 发起支付
type CreatePayReq struct {
	OrderNo    string `json:"order_no" vd:"len($)>0"`
	Amount     int64  `json:"amount" vd:"$>0"`
	PayChannel string `json:"pay_channel" vd:"$=='alipay' || $=='wechat'"`
}

type CreatePayResp struct {
	PaymentNo  string `json:"payment_no"`
	QrCode     string `json:"qr_code"`
	ExpireTime int64  `json:"expire_time"`
}

// 查询支付状态
type GetPayStatusReq struct {
	PaymentNo string `path:"payment_no"`
}

type GetPayStatusResp struct {
	PaymentNo  string `json:"payment_no"`
	Status     int32  `json:"status"`
	StatusText string `json:"status_text"`
	Amount     int64  `json:"amount"`
	OrderNo    string `json:"order_no"`
}

// 取消支付
type CancelPayReq struct {
	PaymentNo string `path:"payment_no"`
}

type CancelPayResp struct {
	Message string `json:"message"`
}

// 支付记录列表
type ListPayReq struct {
	Page     int32 `form:"page,optional"`
	PageSize int32 `form:"page_size,optional"`
}

type ListPayResp struct {
	Payments []PaymentInfo `json:"payments"`
	Total    int32         `json:"total"`
	Page     int32         `json:"page"`
	PageSize int32         `json:"page_size"`
}

// ============================================
// 订单相关类型
// ============================================

type OrderItem struct {
	Id          int64  `json:"id"`
	OrderNo     string `json:"order_no"`
	ProductId   int64  `json:"product_id"`
	ProductName string `json:"product_name"`
	Count       int32  `json:"count"`
	TotalAmount int64  `json:"total_amount"`
	Status      int32  `json:"status"`
	StatusText  string `json:"status_text"`
	CreateTime  int64  `json:"create_time"`
	PayTime     int64  `json:"pay_time"`
}

// 订单列表
type ListOrderReq struct {
	Page     int32 `form:"page,optional"`
	PageSize int32 `form:"page_size,optional"`
	Status   int32 `form:"status,optional"`
}

type ListOrderResp struct {
	Orders   []OrderItem `json:"orders"`
	Total    int32       `json:"total"`
	Page     int32       `json:"page"`
	PageSize int32       `json:"page_size"`
}

// 订单详情
type GetOrderDetailReq struct {
	OrderNo string `form:"order_no,optional"`
}

type GetOrderDetailResp struct {
	Id            int64  `json:"id"`
	OrderNo       string `json:"order_no"`
	ProductId     int64  `json:"product_id"`
	ProductName   string `json:"product_name"`
	ProductDesc   string `json:"product_desc"`
	ProductImage  string `json:"product_image"`
	Count         int32  `json:"count"`
	TotalAmount   int64  `json:"total_amount"`
	Status        int32  `json:"status"`
	StatusText    string `json:"status_text"`
	CreateTime    int64  `json:"create_time"`
	PayTime       int64  `json:"pay_time"`
	ExpireTime    int64  `json:"expire_time"`
}

// 取消订单
type CancelOrderReq struct {
	OrderNo string `json:"order_no,optional"`
}

type CancelOrderResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

// ============================================
// 收货地址相关类型
// ============================================

type AddressItem struct {
	Id            int64  `json:"id"`
	ReceiverName  string `json:"receiver_name"`
	Phone         string `json:"phone"`
	Province      string `json:"province"`
	City          string `json:"city"`
	District      string `json:"district"`
	DetailAddress string `json:"detail_address"`
	PostalCode    string `json:"postal_code"`
	IsDefault     bool   `json:"is_default"`
}

type GetAddressListReq struct {
	UserId int64 `json:"user_id"`
}

type GetAddressListResp struct {
	Addresses []AddressItem `json:"addresses"`
}

type GetAddressReq struct {
	Id int64 `path:"id"`
}

type GetAddressResp struct {
	Address AddressItem `json:"address"`
}

type AddAddressReq struct {
	ReceiverName  string `json:"receiver_name" vd:"len($)>0"`
	Phone         string `json:"phone" vd:"len($)>0"`
	Province      string `json:"province" vd:"len($)>0"`
	City          string `json:"city" vd:"len($)>0"`
	District      string `json:"district" vd:"len($)>0"`
	DetailAddress string `json:"detail_address" vd:"len($)>0"`
	PostalCode    string `json:"postal_code,optional"`
	IsDefault     bool   `json:"is_default"`
}

type AddAddressResp struct {
	Id      int64  `json:"id"`
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type UpdateAddressReq struct {
	Id            int64  `json:"id" vd:"$>0"`
	ReceiverName  string `json:"receiver_name" vd:"len($)>0"`
	Phone         string `json:"phone" vd:"len($)>0"`
	Province      string `json:"province" vd:"len($)>0"`
	City          string `json:"city" vd:"len($)>0"`
	District      string `json:"district" vd:"len($)>0"`
	DetailAddress string `json:"detail_address" vd:"len($)>0"`
	PostalCode    string `json:"postal_code,optional"`
	IsDefault     bool   `json:"is_default"`
}

type UpdateAddressResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type DeleteAddressReq struct {
	Id int64 `path:"id"`
}

type DeleteAddressResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type SetDefaultAddressReq struct {
	Id int64 `json:"id" vd:"$>0"`
}

type SetDefaultAddressResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

// ============================================
// RPC 调用类型（用于调用 address rpc 服务）
// ============================================

type RpcAddressItem struct {
	Id            int64  `json:"id"`
	ReceiverName  string `json:"receiver_name"`
	Phone         string `json:"phone"`
	Province      string `json:"province"`
	City          string `json:"city"`
	District      string `json:"district"`
	DetailAddress string `json:"detail_address"`
	PostalCode    string `json:"postal_code"`
	IsDefault     bool   `json:"is_default"`
}

type RpcGetAddressListReq struct {
	UserId int64 `json:"user_id"`
}

type RpcGetAddressListResp struct {
	Addresses []*RpcAddressItem `json:"addresses"`
}

type RpcAddAddressReq struct {
	UserId        int64  `json:"user_id"`
	ReceiverName  string `json:"receiver_name"`
	Phone         string `json:"phone"`
	Province      string `json:"province"`
	City          string `json:"city"`
	District      string `json:"district"`
	DetailAddress string `json:"detail_address"`
	PostalCode    string `json:"postal_code"`
	IsDefault     bool   `json:"is_default"`
}

type RpcAddAddressResp struct {
	Id      int64  `json:"id"`
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type RpcUpdateAddressReq struct {
	Id            int64  `json:"id"`
	UserId        int64  `json:"user_id"`
	ReceiverName  string `json:"receiver_name"`
	Phone         string `json:"phone"`
	Province      string `json:"province"`
	City          string `json:"city"`
	District      string `json:"district"`
	DetailAddress string `json:"detail_address"`
	PostalCode    string `json:"postal_code"`
	IsDefault     bool   `json:"is_default"`
}

type RpcUpdateAddressResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type RpcDeleteAddressReq struct {
	Id     int64 `json:"id"`
	UserId int64 `json:"user_id"`
}

type RpcDeleteAddressResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}
