Name: order-cron
ListenOn: 0.0.0.0:8889
DataSource: root:root123456@tcp(mysql:3306)/ecommerce_demo?charset=utf8mb4&parseTime=True&loc=Local
RedisHost: redis-cluster:6379
RedisPass: redis123456

# OpenTelemetry 链路追踪配置
Telemetry:
  Name: order-cron.rpc
  Endpoint: http://jaeger:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger
