// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: product.proto

package product

import (
	"context"

	"ecommerce-demo/app/product/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetProductReq         = pb.GetProductReq
	GetProductResp        = pb.GetProductResp
	ListProductReq        = pb.ListProductReq
	ListProductResp       = pb.ListProductResp
	AddProductReq         = pb.AddProductReq
	AddProductResp        = pb.AddProductResp
	UpdateProductReq      = pb.UpdateProductReq
	UpdateProductResp     = pb.UpdateProductResp
	DeleteProductReq      = pb.DeleteProductReq
	DeleteProductResp     = pb.DeleteProductResp
	ListProductByPageReq  = pb.ListProductByPageReq
	ListProductByPageResp = pb.ListProductByPageResp
	GetCategoriesReq      = pb.GetCategoriesReq
	GetCategoriesResp     = pb.GetCategoriesResp
	AddCategoryReq        = pb.AddCategoryReq
	AddCategoryResp       = pb.AddCategoryResp
	ProductItem           = pb.ProductItem
	Category              = pb.Category

	Product interface {
		// 获取商品详情 (这个接口后面我们会做 Redis 高并发缓存)
		GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error)
		// 获取商品列表
		ListProduct(ctx context.Context, in *ListProductReq, opts ...grpc.CallOption) (*ListProductResp, error)
		// 添加商品
		AddProduct(ctx context.Context, in *AddProductReq, opts ...grpc.CallOption) (*AddProductResp, error)
		// 更新商品
		UpdateProduct(ctx context.Context, in *UpdateProductReq, opts ...grpc.CallOption) (*UpdateProductResp, error)
		// 删除商品
		DeleteProduct(ctx context.Context, in *DeleteProductReq, opts ...grpc.CallOption) (*DeleteProductResp, error)
		// 分页获取商品列表
		ListProductByPage(ctx context.Context, in *ListProductByPageReq, opts ...grpc.CallOption) (*ListProductByPageResp, error)
		// 获取商品分类
		GetCategories(ctx context.Context, in *GetCategoriesReq, opts ...grpc.CallOption) (*GetCategoriesResp, error)
		// 添加商品分类
		AddCategory(ctx context.Context, in *AddCategoryReq, opts ...grpc.CallOption) (*AddCategoryResp, error)
	}

	defaultProduct struct {
		cli zrpc.Client
	}
)

func NewProduct(cli zrpc.Client) Product {
	return &defaultProduct{
		cli: cli,
	}
}

// 获取商品详情 (这个接口后面我们会做 Redis 高并发缓存)
func (m *defaultProduct) GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error) {
	client := pb.NewProductClient(m.cli.Conn())
	return client.GetProduct(ctx, in, opts...)
}

// 获取商品列表
func (m *defaultProduct) ListProduct(ctx context.Context, in *ListProductReq, opts ...grpc.CallOption) (*ListProductResp, error) {
	client := pb.NewProductClient(m.cli.Conn())
	return client.ListProduct(ctx, in, opts...)
}

// 添加商品
func (m *defaultProduct) AddProduct(ctx context.Context, in *AddProductReq, opts ...grpc.CallOption) (*AddProductResp, error) {
	client := pb.NewProductClient(m.cli.Conn())
	return client.AddProduct(ctx, in, opts...)
}

// 更新商品
func (m *defaultProduct) UpdateProduct(ctx context.Context, in *UpdateProductReq, opts ...grpc.CallOption) (*UpdateProductResp, error) {
	client := pb.NewProductClient(m.cli.Conn())
	return client.UpdateProduct(ctx, in, opts...)
}

// 删除商品
func (m *defaultProduct) DeleteProduct(ctx context.Context, in *DeleteProductReq, opts ...grpc.CallOption) (*DeleteProductResp, error) {
	client := pb.NewProductClient(m.cli.Conn())
	return client.DeleteProduct(ctx, in, opts...)
}

// 分页获取商品列表
func (m *defaultProduct) ListProductByPage(ctx context.Context, in *ListProductByPageReq, opts ...grpc.CallOption) (*ListProductByPageResp, error) {
	client := pb.NewProductClient(m.cli.Conn())
	return client.ListProductByPage(ctx, in, opts...)
}

// 获取商品分类
func (m *defaultProduct) GetCategories(ctx context.Context, in *GetCategoriesReq, opts ...grpc.CallOption) (*GetCategoriesResp, error) {
	client := pb.NewProductClient(m.cli.Conn())
	return client.GetCategories(ctx, in, opts...)
}

// 添加商品分类
func (m *defaultProduct) AddCategory(ctx context.Context, in *AddCategoryReq, opts ...grpc.CallOption) (*AddCategoryResp, error) {
	client := pb.NewProductClient(m.cli.Conn())
	return client.AddCategory(ctx, in, opts...)
}
