Name: cart.rpc
ListenOn: 0.0.0.0:8083

Etcd:
  Hosts:
    - etcd:2379
  Key: cart.rpc

RedisConf:
  Host: redis-cluster:6379
  Type: node
  Pass: "redis123456"
  DB: 0

# OpenTelemetry 链路追踪配置
Telemetry:
  Name: cart.rpc
  Endpoint: http://jaeger:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger
