---
# ServiceMonitor - API Gateway
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: gateway
  namespaceSelector:
    matchNames:
      - ecommerce
  endpoints:
    - port: gateway
      path: /metrics
      interval: 15s
---
# ServiceMonitor - User Service
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: user
  namespaceSelector:
    matchNames:
      - ecommerce
  endpoints:
    - port: user
      interval: 15s
---
# ServiceMonitor - Product Service
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: product
  namespaceSelector:
    matchNames:
      - ecommerce
  endpoints:
    - port: product
      interval: 15s
---
# ServiceMonitor - Order Service
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: order
  namespaceSelector:
    matchNames:
      - ecommerce
  endpoints:
    - port: order
      interval: 15s
---
# ServiceMonitor - Stock Service
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stock-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: stock
  namespaceSelector:
    matchNames:
      - ecommerce
  endpoints:
    - port: stock
      interval: 15s
---
# ServiceMonitor - Cart Service
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cart-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: cart
  namespaceSelector:
    matchNames:
      - ecommerce
  endpoints:
    - port: cart
      interval: 15s
---
# ServiceMonitor - Payment Service
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: payment
  namespaceSelector:
    matchNames:
      - ecommerce
  endpoints:
    - port: payment
      interval: 15s
---
# ServiceMonitor - Address Service
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: address-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: address
  namespaceSelector:
    matchNames:
      - ecommerce
  endpoints:
    - port: address
      interval: 15s
