// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package server

import (
	"context"

	"ecommerce-demo/app/order/internal/logic"
	"ecommerce-demo/app/order/internal/svc"
	"ecommerce-demo/app/order/pb"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) CreateOrder(ctx context.Context, in *pb.CreateOrderReq) (*pb.CreateOrderResp, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

func (s *OrderServer) ConfirmPay(ctx context.Context, in *pb.ConfirmPayReq) (*pb.ConfirmPayResp, error) {
	l := logic.NewConfirmPayLogic(ctx, s.svcCtx)
	return l.ConfirmPay(in)
}

func (s *OrderServer) ListOrder(ctx context.Context, in *pb.ListOrderReq) (*pb.ListOrderResp, error) {
	l := logic.NewListOrderLogic(ctx, s.svcCtx)
	return l.ListOrder(in)
}

func (s *OrderServer) GetOrderDetail(ctx context.Context, in *pb.GetOrderDetailReq) (*pb.GetOrderDetailResp, error) {
	l := logic.NewGetOrderDetailLogic(ctx, s.svcCtx)
	return l.GetOrderDetail(in)
}

func (s *OrderServer) CancelOrder(ctx context.Context, in *pb.CancelOrderReq) (*pb.CancelOrderResp, error) {
	l := logic.NewCancelOrderLogic(ctx, s.svcCtx)
	return l.CancelOrder(in)
}
